#!/bin/sh

user="rayqiao"
host=""
work_dir=`pwd`
src_path=""
src_file=""
dest_path=""
gorsync()
{
	line=`grep $host ~/bin/hostkeys.conf | grep $user `
	if [ -z "${line}" ];then
		echo "$host $user not found in hostkeys.conf" 
		exit
	fi
	host=`echo ${line} | awk '{print $1}'`
	passwd=`echo ${line} |awk '{print $3}'`
	ip=`echo ${host} | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}"`
	cd `dirname ${src_path}`
	if [ -z "$ip" ];then
		echo $PATH
		autorsync.expect $user $host $passwd $src_file $dest_path
	else
		autorsync.inner.expect $user $host $passwd $src_file $dest_path
	fi
	cd ${work_dir}
}
if [ $# -lt 3 ];then
	echo "Usage gorsync SRC_PATH DEST_HOST DEST_PATH DEST_USER(DEFALUT rayqiao)"
	exit
elif [ $# = 4 ];then
	user="$4"
fi
src_path=$1
src_file=`basename $1`
host=$2
dest_path=$3
#cd ~/bin
gorsync
