#!/bin/sh

user="rayqiao"
host=""
login()
{
	line=`grep $host hostkeys.conf | grep $user `
	if [ -z "${line}" ];then
		echo "$host $user not found in hostkeys.conf" 
		exit
	fi
	cnt=`grep $host hostkeys.conf | grep $user | wc -l`
	if [ $cnt -gt 1 ];then
		echo "$line" 
		exit
	fi
	host=`echo ${line} | awk '{print $1}'`
	passwd=`echo ${line} |awk '{print $3}'`
	ip=`echo ${host} | egrep -o "[0-9.]+"`
	if [ "X"$ip!="X" ];then
		./autossh.inner.expect $user $host $passwd
	else
		./autossh.expect $user $host $passwd
	fi
}
if [ $# = 0 ];then
	echo "Usage gosh HOST USER(DEFALUT rayqiao)"
	exit
elif [ $# = 2 ];then
	user="$2"
fi
host=$1
cd ~/bin
login
